### ISSUE TITLE
Include a screenshot of the application on the website

### ISSUE THREAD

**Issue by sesh** [standardnotes/website#1]
I love the minimal look of the website, but I feel that the user experience would be greatly improved if the user could see a screenshot of the application before downloading it.

This applies for the desktop app, primarily, but could also apply to the mobile version.

I, for one, am hesitant to download applications until I know what they look like.

**Comment by mobitar** [comment]
That's good feedback, thanks. You can try out the app without install on https://app.standardnotes.org, but we should make that clearer.

**Comment by mobitar** [comment]
Done
