### ISSUE TITLE
Use Markdown Preview by default

### ISSUE THREAD

**Issue by lewdev** [standardnotes/website#10]
Great app, thank you for building this!

Just as a suggestion, please have an option to initially show notes in Markdown preview mode so that I can browse my notes in that view, then when I want edit it, I can click on the note to change it to Edit mode.

**Comment by mobitar** [comment]
Thanks Lewis, please join the club at https://github.com/standardnotes/web/issues/31 ;)

More comments here https://github.com/standardnotes/web/pull/54

**Comment by lewdev** [comment]
Wow, that was a super fast response! Thanks!
