### ISSUE TITLE
Does not work without JavaScript

### ISSUE THREAD

**Issue by user6529576559** [standardnotes/website#2]
Hello,

The whole website is broken, I cannot see anything without JavaScript enabled. It should work without JS, because it is not needed for this kind of site and also it causes issues for NoScript (which includes Tor Browser) users.

**Comment by mobitar** [comment]
True, it isn't needed, but right now I'm using to also host /extensions and /tools, which do use Javascript. So until I can decouple those, I'll have to continue using JS.
