### ISSUE TITLE
Align Apple icon with other icons

### ISSUE THREAD

**Issue by theratris** [standardnotes/website#9]
Hi my OCD is speaking here but it would look a bit nicer to align the apple logo with the other logos.

Add this inline style to the second div.download-item:
style="position:relative; top: 26px;"

Expected result:
![capture](https://cloud.githubusercontent.com/assets/6717350/22410470/469ed43c-e65e-11e6-875a-bd64c71204c2.PNG)

If you have any other odd jobs needing done let me know. I would love to help :)

**Comment by mobitar** [comment]
<img width="600" alt="screen shot 2017-01-30 at 7 52 21 am" src="https://cloud.githubusercontent.com/assets/3277844/22425515/0b7c833c-e6c1-11e6-812e-31fb98f0b6be.png">

Looks like this when the window is a little wider. But you're right when the window shrinks it looks funny.

**Comment by theratris** [comment]
Ah my mistake I should have tested it more.

**Comment by mobitar** [comment]
No worries, should be fixed either way.

**Comment by mobitar** [comment]
Fixed
